config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  self.per_page = 20

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Before filters
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = I18n.t('flash.messages.welcome')
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = I18n.t('flash.messages.profile_updated')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by(id:params[:id])
    if @user
      @user.destroy
      flash[:success] = I18n.t('flash.messages.user_deleted')
    else
      flash[:danger] = I18n.t('flash.messages.user_not_exist')
    end
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = I18n.t("flash.messages.log_in")
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.haml
= form_for(@user, url: yield(:form_url)) do |f|
  = render 'shared/error_messages', object: @user

  = f.label :name
  = f.text_field :name, class: 'form-control'

  = f.label :email
  = f.email_field :email, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.label :password_confirmation, "Confirmation"
  = f.password_field :password_confirmation, class: 'form-control'

  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |
    = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.haml
- provide(:title, "Edit user")
- provide(:button_text, "Save changes")
- provide(:form_url, user_path)
%h1 Update your profile

%div.row
  %div.col-md-6.col-md-offset-3
    = render 'form'

    %div.gravatar_edit
      = gravatar_for @user
      %a{href:"http://gravatar.com/emails", target:"_blank", rel:"noopener"}
        change

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users

= will_paginate
%ul.users
  - @users.each do |user|
    = render user

= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
- provide(:button_text, 'Create my account')
- provide(:form_url, signup_path)
%h1 Sign up
%div.row
  %div.col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.haml
= provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user, {size:100}
        = @user.name
  .col-md-8
    - if @user.microposts.any?
      %h3
        Microposts (
        = @user.microposts.count
        )
      %ol.microposts
        = render @microposts
      = will_paginate @microposts