config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{href:"http://www.railstutorial.org/"} Ruby on Rails Tutorial
    by
    %a{href:"http://www.michaelhartl.com/"} Michael Hartl
  %nav
    %ul
      %li
        = link_to "About", about_path
      %li
        = link_to "Contact", contact_path
      %li
        %a{href:"http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %div.container
    = link_to "sample app", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        %li
          = link_to "Help", help_path


        - if logged_in?
          %li
            = link_to "Users", users_path
          %li.dropdown
            %a{ href:"#", class:"dropdown-toggle", "data-toggle":"dropdown" }
              Account
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Profile", current_user
              %li
                = link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: "delete"
        - else
          %li
            = link_to "Log in", login_path

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js'></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }
    %title
      = full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    %div.container
      - flash.each do |message_type, message|
        %div{ class: "alert alert-#{message_type}" }
          = message

      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?